name: genmob
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - pandas
  - nb_conda
  - geopandas
  - matplotlib
  - descartes
  - xlrd
  - scikit-learn
  - pydeck
  - pip
  - pip:
    - correlaidmatplotlib
  