name: genmob
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - pandas
  - geopandas
  - matplotlib
  - descartes
  - xlrd
  - scikit-learn
  - pydeck
# dependencies from cookiecutter
#  - click
#  - Sphinx
#  - coverage
#  - awscli
#  - flake8
#  - python-dotenv>=0.5.1